name: CI
on:
  push:

jobs:
  container-test-job:
    runs-on: jph-self-hosted
    container:
      image: cfsbuildenv-ubuntu22:test

    steps:
      - name: Say Hello
        run: echo "Hello, world"
 
